services:
  - type: web
    name: portal-academico
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Redis__ConnectionString
        sync: false
